### PR TITLE
fix: method names & verbose logging

### LINKED ISSUE #306: Logging error when running Python `Updater` in `verbose == True` mode
I ran into an error in `diagnostic_updater/diagnostic_updater/_diagnostic_updater.py` when setting `Updater.verbose` to `True`. I get the following error.

```bash
Traceback (most recent call last):
File "/workspaces/humble/install/argos_supervisor_py/lib/argos_supervisor_py/supervisor", line 33, in <module>
  sys.exit(load_entry_point('argos-supervisor-py', 'console_scripts', 'supervisor')())
File "/workspaces/humble/build/argos_supervisor_py/argos_supervisor_py/supervisor_node.py", line 280, in main
  executor.spin()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 279, in spin
  self.spin_once()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 764, in spin_once
  self._spin_once_impl(timeout_sec)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 761, in _spin_once_impl
  future.result()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 94, in result
  raise self.exception()
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
  self._handler.send(None)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 418, in handler
  await call_coroutine(entity, arg)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 332, in _execute_timer
  await await_or_execute(tmr.callback)
File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
  return callback(*args)
File "/workspaces/humble/install/diagnostic_updater/local/lib/python3.10/dist-packages/diagnostic_updater/_diagnostic_updater.py", line 279, in update
  'Non-zero diagnostic status. Name: %s, status\
TypeError: %i format: a real number is required, not bytes
```

The issue is within the following lines.

https://github.com/ros/diagnostics/blob/c8941bb72bef2309dee04a63c55f5b4437329632/diagnostic_updater/diagnostic_updater/_diagnostic_updater.py#L278-L281

Because `status.level` is a `byte`, but `%i` requires a number. Explicitly converting the byte to a string and using `%s` would fix this issue.

I'm more than happy to open a PR with these changes 😄

### PR DESCRIPTION
**Pull request by KevinSchwarzer**
Fixes #306.

### CODE REVIEW

**Comment by KevinSchwarzer** [comment]
@ct2034, the [focal build fails](https://build.ros2.org/job/Fpr__diagnostics__ubuntu_focal_amd64/124/console#console-section-9) due to a rosdep key error.

**Comment by ct2034** [comment]
Okay. Let's ignore the foxy build for now.
What would be a good test that would check the issue, you raised?

**Comment by KevinSchwarzer** [comment]
> What would be a good test that would check the issue, you raised?

@ct2034, we could use [`launch_testing`](https://github.com/ros2/launch/tree/rolling/launch_testing), with which we could [check stdout/stderr](https://github.com/ros2/launch/tree/rolling/launch_testing#exit-codes-and-standard-out). I'm not familiar with the package, though; at our company we use a similar package, [`launch_pytest`](https://github.com/ros2/launch/tree/rolling/launch_pytest), which integrates nicely with `pytest`. However, I should be able to come up with a simple test checking for the log message in stdout depending on whether `verbose` is set to `True`.

**Comment by ct2034** [comment]
This would be awesome

**Comment by KevinSchwarzer** [comment]
@ct2034, let me know what you think of the test.

**Review by ct2034 — APPROVED** [review]
Lgtm

**Pull request merged**
