### PR TITLE
Instal example publisher for diagnostic_aggregator example as a program.

### PR DESCRIPTION
**Pull request by airballking**
Fixes https://github.com/ros/diagnostics/issues/156

### CODE REVIEW

**Comment by airballking** [comment]
@Karsten1987 Some of the automatic checks failed. My naive take is that this is not caused by this PR. How to continue?

**Comment by Karsten1987** [comment]
I honestly don't know at this point what's the right configuration for the GH actions. I'll have to look into them, whether I manage to update to a newer version or disable them temporarily. 

As for the patch, I think this looks good. Another thing I had to change was the shebang line in order to make it work on my OSX:
```
diff --git a/diagnostic_aggregator/example/example_pub.py b/diagnostic_aggregator/example/example_pub.py
index 35f04e3..9751a56 100755
--- a/diagnostic_aggregator/example/example_pub.py
+++ b/diagnostic_aggregator/example/example_pub.py
@@ -1,4 +1,4 @@
-#!/usr/bin/python3
+#!/usr/bin/env python3
 # -*- coding: utf-8 -*-

 # Software License Agreement (BSD License)
```

Do you mind addressing this in your patch as well?

**Comment by Karsten1987** [comment]
If you rebase your branch on top of ros2-devel, I believe the checks should all pass. 
That being said, please target your branch against `ros2-devel` and we'll backport the fix to `foxy` and cut a release.

**Comment by airballking** [comment]
@Karsten1987 Thanks for the quick response and fix of the GH actions!

Sure, I can target the ros2-devel branch. Unfortunately, rebasing my branch onto ros2-devel leads to a small merge conflict. There seems to be a conflict between the upstream foxy and ros2-devel branches. I guess you want to resolve that yourself in your backport. So, I'll just cherry-pick my commit in a new branch and open a new pull request. That will also include the fix for the she-bang line.

**Pull request closed without merging**
