### PR TITLE
common_diagnostics cleaned hostname string

### LINKED ISSUE #404: common_diagnostics CPU monitoring fails on hostname with added domain
The hostname generated by `socket.gethostname()` can contain non-alphanumeric symbols, e.g. when a domain is added: hostname.domain.com
Currently, the cpu, ram and sensor monitoring fail due to incomplete string sanitation.

Solution: 
Better string sanitation for all common_diagnostics nodes (also adds more consistent behavior)

### PR DESCRIPTION
**Pull request by sjusner**
fixes #404. hostname used for node name now only contains alphanumeric and underscore.
Did not introduced any new libraries, also avoided python 3.7 specific feature for compatibility.

### CODE REVIEW

**Comment by Timple** [comment]
Just curious, for compatibility with what?

There are no active ROS distributions on python versions older than 3.8

**Comment by sjusner** [comment]
Oh, that's true. Somehow I was thinking about the 3.6 requirements of ROS 2.
In that case I'll adapt the change, as the readability will be improved.

**Review by ct2034 — APPROVED** [review]
Thanks for your contribution

**Comment by ct2034** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|ros2-humble|[](https://github.com/ros/diagnostics/pull/419)|
|✅|ros2-iron|[](https://github.com/ros/diagnostics/pull/420)|
|✅|ros2-jazzy|[](https://github.com/ros/diagnostics/pull/421)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
