### PR TITLE
Aggregator bugfix, tests, and nicer example

### PR DESCRIPTION
**Pull request by norro**
* Fixes toplevel status calculation in the aggregator, see https://github.com/ros/diagnostics/issues/146
* Adds additional tests that test the actual aggregator output, i.e. the produced diagnostic messages
* Example now nicer and more fun to watch in the robot monitor

### CODE REVIEW

**Comment by Karsten1987** [comment]
@norro do you mind updating the GH actions to the latest version - I think v23/v17?
```
      - uses: ros-tooling/setup-ros@0.0.23
      - uses: ros-tooling/action-ros-ci@0.0.17
```

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11335/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6573/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9299/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11232/)

**Comment by Karsten1987** [comment]
@norro you might want to re-iterate once more over the windows tests :P

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11355/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6585/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9310/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11246/)

**Review by Karsten1987 — APPROVED** [review]

**Comment by Karsten1987** [comment]
@norro can you come up with a backport PR of this? I feel like the "bugfix" part of this PR should be backported to Foxy.

**Comment by norro** [comment]
Sure, good point.

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2020-07-16/15468/1

**Pull request merged**
