### PR TITLE
Fix per-bond topic name in add_analyzers.

### PR DESCRIPTION
**Pull request by Jin-Myung**
This PR fixes the bond topic name mismatch in the add_analyzers script caused by https://github.com/Jin-Myung/diagnostics/commit/a6ea1b6e1c8062d044ae28d172aea6d4305065aa.

### CODE REVIEW

**Comment by trainman419** [comment]
Oops. I upstreamed these changes from a private repository, and it looks like I missed the changes to add_analyzers. I'll update with the full fix shortly.

**Comment by trainman419** [comment]
Fixed in 3275b51

**Comment by Jin-Myung** [comment]
Thanks!

**Comment by jwon02** [comment]
@trainman419 Is it possible to tag this repo?

**Comment by trainman419** [comment]
@jwon02 I don't understand what you're asking. Why do you want me to "tag the repo" ?

**Comment by jwon02** [comment]
I was wondering if I could have 1.9.3 that comes with the fix against the add_analyzers issue.

**Pull request closed without merging**
