### PR TITLE
make rostest in CMakeLists optional (ros/rosdistro#3010)

### PR DESCRIPTION
**Pull request by bulwahn**

### CODE REVIEW

**Comment by vrabaud** [comment]
@trainman419  , why hasn't that been merged ? it's totally valid

**Comment by trainman419** [comment]
The previous pull requests from @bulwahn broke the package's public API, and after spending days fixing those, I was out of energy to review any more pull requests from him.

See #11, #16, #24 and #28.

**Comment by trainman419** [comment]
I also go no feedback or help from @bulwahn on #27, #28 or #30.

**Comment by vrabaud** [comment]
oh wow ! Damn, a lot of mess ! This PR is what is done elsewhere though.

**Comment by tfoote** [comment]
I've reviewed the PR, it looks consistent with the others. +1 for merge.

**Comment by trainman419** [comment]
This needs to be resubmitted against master.

**Pull request closed without merging**
