### PR TITLE
Ros2 migrate diagnostic aggregator

### PR DESCRIPTION
**Pull request by Karsten1987**
This is currently still work in progress in order to make all tests pass.

This PR requires https://github.com/ros/bond_core/pull/54

### CODE REVIEW

**Comment by norro** [comment]
@Karsten1987 can you fix the jenkins setup so that this PR builds against the proper bondcpp PR? I don't know how to that tbh.

**Comment by Karsten1987** [comment]
@norro the current PR compiles and passes all linters. However, the test doesn't pass. It's essentially because it can't find the appropriate parameter:

```
  std::map<std::string, rclcpp::Parameter> parameters;
  if (!n->get_parameters(breadcrumb_, parameters)) {
    RCLCPP_WARN(logger_,
      "Couldn't retrieve parameters for analyzer group '%s', namespace '%s'.",
      breadcrumb_.c_str(), n->get_namespace());
    return false;
  }
```

Do you know what parameter should be set here?

**Comment by norro** [comment]
> Do you know what parameter should be set here?

This test requires a parameters yaml file, e.g., `all_basic_analyzers.yaml`. I tried to set this up with launch-testing, but failed.
I added a demo launch setup that should show what I wanted to do for the test as well, see PR in the downstream repo: https://github.com/boschresearch/ros2_diagnostics/pull/3

I can't properly test this right now, as somehow the plugin loading seems to be broken right now for me (it was working before an install folder cleanup I just did, probably was working due to some legacy files in my install folder).

**Comment by Karsten1987** [comment]
@norro @ralph-lange This PR compiles but has quite some test failures in `flake8` and `copyright`. Do you plan on addressing them? I think we've talked about not having python support due to the lack of `bondpy`. I would therefore propose to cleanup the unused python files in order to have a clean state with all passing linters/test before merging this PR.

**Comment by norro** [comment]
@Karsten1987 Agreed. Should we remove the diagnostic_aggregator python stuff from the branch entirely then? (of course keeping the python scripts for the example and testing)

Regarding the copyright notices: the respective colcon test (I think `ament_copyright`) is complaining about a lot of hpp files that have a copyright notice in them. It is an old notice (willow garage, 2008), but still. do you know how to address these? they are the same as in the other diagnostic_* packages hpp files.

**Comment by Karsten1987** [comment]
I think it's okay to delete the unused python stuff from this branch. We can open a follow-up github ticket to revive the python aggregator functionality once `bond_py` is ported. I think it's sufficient to limit the scope of this PR to C++.

As for the copyright linters: You can disable them specifically per project by adding this line to the `CMakeLists.txt`: `set(ament_cmake_copyright_FOUND TRUE)`.

Please make sure to run `colcon build` as well as `colcon test` locally to see that all linters pass before we can trigger CI here and bring this PR forward.

**Comment by norro** [comment]
@Karsten1987 I removed the python stuff accordingly, all tests/checks running without errors.
I build against [boschresearch/bond_core#fix_ros2](https://github.com/boschresearch/bond_core/tree/fix_ros2), which I suggest merging to ros/bondcore as well.

**Comment by Karsten1987** [comment]
~@norro could you please rebase this branch on top of the latest ros2-devel branch?~

I took the liberty to rebase your branch as it's already a fair mix of contributions :)

**Comment by norro** [comment]
Will adapt this branch to foxy now. D'accord, @Karsten1987?

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10530/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5988/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8577/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10397/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10533/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5990/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8579/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10399/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10534/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/5991/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8580/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10401/)

**Comment by Karsten1987** [comment]
thanks @norro for updating the PR to remove Boost. 

In order to be able to run CI, I think we have to tackle the PkgConfig issue on OSX and Windows. Maybe use the same logic for generating `uuid`s as in rclcpp-action?
https://github.com/ros2/rclcpp/blob/814298480c088254a2e7880639fe8412d18530e4/rclcpp_action/src/client.cpp#L377-L379

**Comment by norro** [comment]
@Karsten1987 so we have to kick-out dependency to uuid entirely in order to be platform-independent (i.e. build on mac and win)?

**Comment by Karsten1987** [comment]
I just did a little google search around that topic (cross-platform uuid generation) and did not really find a compelling way to do so without any dependencies to external libraries.

I found https://lowrey.me/guid-generation-in-c-11/ which display a quick way (similar to what is done in rclcpp_action) which generates a random UUID with standard c++11 tools.

**Comment by norro** [comment]
@Karsten1987 I am realising just now that uuid might have been pulled in for bond. Will test it tomorrow, it might be possible to just get rid of the dependency.

**Comment by norro** [comment]
I was able to remove the uuid dependency, this issue doesn't seem to block the builds anymore.

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10572/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6023/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8610/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10471/)

**Comment by Karsten1987** [comment]
@norro Build looks good so far. I think there's something Linux specific in the `CMakeLists.txt`:
```
# see https://github.com/pybind/pybind11/commit/ba33b2fc798418c8c9dfe801c5b9023d3703f417
target_compile_options(${PROJECT_NAME} PRIVATE -Wdeprecated)
```

`-Wdeprecated` is not supported on Windows. That needs a special treatment.

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10604/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6045/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8635/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10500/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10610/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6050/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8640/)  // CI hiccup
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10505/)

**Comment by Karsten1987** [comment]
@norro so your PR builds now on all platforms. There are a non-zero amount of failing tests on Windows. Please have a look at them. 

There's a known problem with sending `Ctrl-C` commands to a test in windows. So if you expect work to be done in a destructor or something, that might be a problem here. If there's no easy workaround, we might have to disable the tests on Windows.

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10798/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6183/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8791/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10687/)

**Comment by norro** [comment]
Sorry, used the wrong path magic. Can you check again, please, @Karsten1987.

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10799/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6184/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8792/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10688/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10971/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6310/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8932/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10878/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10975/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6313/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8936/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10881/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10985/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6321/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8944/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10891/)

**Comment by Karsten1987** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10991/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6327/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8950/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10899/)

**Comment by norro** [comment]
Looks like the last Windows build failing was due to a hicc-up in the build setup (pip installation of dependencies).

**Comment by Karsten1987** [comment]
Windows once more: [Build Status](https://ci.ros2.org/job/ci_windows/10917/)  // These warnings are unrelated.

**Comment by norro** [comment]
*whoop*

**Comment by Karsten1987** [comment]
@norro can that branch be deleted?

**Comment by norro** [comment]
absolutely.

**Pull request merged**
