### PR TITLE
Test ntp monitor

### PR DESCRIPTION
**Pull request by RFRIEDM-Trimble**
* Refactor some functions to be more testable
* Fix a failure for parsing empty output that was trying to index a Null
value
* Use 1E6 rather than 1000000
* Add dependency on pytest
* Fix rosdep depdendency issues for existing keys (removed some duplicates, etc)
* Add tests support to run from ament_cmake_pytest
* Add missing timestamp for header from ROS2 port
* Solves https://github.com/ros/diagnostics/issues/254

### CODE REVIEW

**Comment by ct2034** [comment]
Hi @RFRIEDM-Trimble, thanks again for your contribution.
Could you please change your pr to be towards ros2 and update your branch with it. Then please request my review

**Comment by ct2034** [comment]
> Hi @RFRIEDM-Trimble, thanks again for your contribution. Could you please change your pr to be towards ros2 and update your branch with it. Then please request my review

nvm. I have the power now ;-)

**Comment by ct2034** [comment]
This is no longer needed since we are not using plain `ntpdate` any more.

**Comment by Ryanf55** [comment]
> This is no longer needed since we are not using plain `ntpdate` any more.

What's the replacement? Sorry, I migrated accounts.

**Comment by ct2034** [comment]
It is now using a python library called `ntplib`. So it is no longer necessary to test the parsing of command line output.

**Pull request closed without merging**
