### PR TITLE
Galactic cmakelist fixed

### PR DESCRIPTION
**Pull request by jage92**
I had problems in ROS2 galactic to find the headers of the self_test node. I need to modify the cmakelist. I used the last galactic commit that has been passed the test.

### CODE REVIEW

**Comment by ct2034** [comment]
Hi @jage92!
Thanks a lot for your contribution.
Could you please merge ros2 into your branch?

**Comment by ralph-lange** [comment]
Hi @jage92, could you please rebase your branch to the ros2 branch. In the current form, the PR has a lot of conflicts and many unwanted changes (e.g., the distros in `.github/workflows/test.yaml`).

**Comment by jage92** [comment]
In this case, the problem was only a line in the `self_test/CMakeList.txt` file. Before the last line, I put `ament_export_include_directories(include)`. Maybe it is easier for you add this line in the development version and ignore the pull request. 

Thank you for your attention.

**Comment by ct2034** [comment]
Closing in favor of #292

**Pull request closed without merging**
