### PR TITLE
Make FrequencyStatus' name configurable

### PR DESCRIPTION
**Pull request by NilsHaukeBussas-TomTom**
I think this is pretty self-explanatory. In some cases you'd like to give the frequency status some other name. This ought to be supported.

### CODE REVIEW

**Comment by mikepurvis** [comment]
Yes please! :+1:

**Comment by trainman419** [comment]
Unfortunately, adding an argument to a method is an ABI-breaking change and would require that this only go into future ROS releases.

If you restructure this as a new constructor that takes two arguments, it won't break ABI and will be releasable for current versions of ROS.

**Comment by NilsHaukeBussas-TomTom** [comment]
I don't want to pressure you, just want to make sure you notice my changes: I updated the patch by amending the commit because it's not additional work but replaces the old implementation. I've been told this might not have triggered a message to you. So, if it didn't, here's the reminder.

**Comment by trainman419** [comment]
Looks good! Thanks for the notification; github isn't good about sending notifications on code changes.

**Pull request merged**
